name: Build for MacOS
on:
  - push

env:
  CI: false


jobs:
  macos:
    runs-on: 'macos-latest'
    steps:
      - name: Fetch DMG
        run: curl -O https://github.com/vorujack/minotaur-2-release-test/releases/download/v1.0.1/minotaur-1.0.1.dmg
      
      - name: List downloaded
        run: ls

      - name: Create P12 Certificate File
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'Minotaur.p12'
          fileDir: '.'
          encodedString: ${{ secrets.CERT_P12 }}

      - name: Create CRT Certificate File
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'Minotaur.crt'
          fileDir: '.'
          encodedString: ${{ secrets.CERT_CRT }}

      - name: Import P12
        run: sudo security import Minotaur.p12 -k "$HOME/Library/Keychains/login.keychain" -P ${{ secrets.CERT_PASS }} -A

      - name: Trust Installed Certificate
        run: sudo security add-trusted-cert -d -r trustRoot -k "$HOME/Library/Keychains/login.keychain" Minotaur.crt
