name: Build for MacOS
on:
  - push

env:
  CI: false


jobs:
  macos:
    runs-on: 'macos-latest'
    steps:
      - name: Fetch DMG
        run: curl -O https://github.com/vorujack/minotaur-2-release-test/releases/download/v1.0.1/minotaur-1.0.1.dmg
      
      - name: List downloaded
        run: ls

      - name: "import certificate"
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERT_P12 }}
          p12-password: ${{ secrets.CERT_PASS }}

      