name: Build for MacOS
on:
  push:
    tags:
      - 'v*.*.*'
      - 'mac-v*.*.*'

env:
  CI: false


jobs:
  macos:
    runs-on: 'macos-latest'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.*

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Update package.json files
        shell: bash
        run: node cli/update_version.js '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}${{ env.PRE_RELEASE }}'

      - name: Install app dependencies
        shell: bash
        run: npm install

      - name: Build Electron
        working-directory: ./electron
        run: npm i; npm run electron:pack

      - name: Create P12 Certificate File
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'Minotaur.p12'
          fileDir: '.'
          encodedString: ${{ secrets.CERT_P12 }}

      - name: Create CRT Certificate File
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'Minotaur.crt'
          fileDir: '.'
          encodedString: ${{ secrets.CERT_CRT }}

      - name: Import P12
        run: sudo security import Minotaur.p12 -k "$HOME/Library/Keychains/login.keychain" -P ${{ secrets.CERT_PASS }} -A

      - name: Trust Installed Certificate
        run: sudo security add-trusted-cert -d -r trustRoot -k "$HOME/Library/Keychains/login.keychain" Minotaur.crt

      - name: Sign And Create DMG
        working-directory: './electron/dist'
        run: codesign -s Minotaur mac/minotaur.app; hdiutil create "./minotaur-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}${{ env.PRE_RELEASE }}-arm64.dmg" -ov -volname "Minotaur" -fs HFS+ -srcfolder "./mac"

      - name: Upload Executable File to release
        uses: softprops/action-gh-release@v1
        with:
          files: electron/dist/minotaur*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
